server {
    listen       4100;
    server_name  localhost;
    root         /usr/share/nginx/html/dist;
    index        index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/sv-asset/(.*)$ {
        rewrite ^/sv-asset/(.*)$ /microfrontends/sv-platform-desktop/sv-asset/$1 last;
    }

    location ~ ^/sv-asset-mob/(.*)$ {
        rewrite ^/sv-asset-mob/(.*)$ /microfrontends/sv-platform-mobile/sv-asset-mob/$1 last;
    }
}
